/**
 * СОЗДАНО АВТОМАТИЧЕСКИ — не редактировать вручную.
 * Генератор: tools/gen-eslint-globals.mjs (разбор AST через acorn)
 *
 * Кросс-файловые глобалы классических скриптов редактора (editor.js ↔
 * enhancer.js ↔ figma_pro_tools.js ↔ inline-скрипты index.html): объявления
 * верхнего уровня одного файла видны остальным как глобальные привязки.
 * Список нужен, чтобы ESLint no-undef ловил только реально отсутствующие имена
 * (класс дефектов P0-2/P0-3), а не легальные кросс-файловые ссылки.
 */
export const PROJECT_GLOBALS = {
  $: 'readonly', // editor.js
  $$: 'readonly', // editor.js
  AI_ELEMENTS_LIBRARY: 'readonly', // editor.js
  CACHE_NAME: 'readonly', // sw.js
  CANVAS_LIMITS: 'readonly', // enhancer.js
  CANVAS_PADDING: 'readonly', // editor.js
  CANVAS_SERIALIZE_PROPS: 'readonly', // editor.js
  COSMO_ITEMS: 'readonly', // editor.js
  CUSTOM_PROPS_TO_SAVE: 'readonly', // editor.js
  DB_NAME: 'readonly', // editor.js
  DB_STORE: 'readonly', // editor.js
  DRAFTS_KEY: 'readonly', // editor.js
  FIGMA_DEFAULT_TOKEN: 'readonly', // editor.js
  FIGMA_STORAGE_KEY: 'readonly', // editor.js
  FONTS: 'readonly', // editor.js
  GRADIENTS: 'readonly', // editor.js
  HDR_PRESETS: 'readonly', // enhancer.js
  LAYER_ICONS: 'readonly', // editor.js
  LOGOS: 'readonly', // editor.js
  MAX_HISTORY: 'readonly', // editor.js
  MODEL_ID: 'readonly', // workers/bg-removal-worker.js
  MODEL_LOAD_TIMEOUT: 'readonly', // workers/bg-removal-worker.js
  PALETTE: 'readonly', // editor.js
  POSTER_DB_NAME: 'readonly', // editor.js
  POSTER_DB_VER: 'readonly', // editor.js
  PRECACHE_ASSETS: 'readonly', // sw.js
  PosterEnhancer: 'readonly', // enhancer.js
  RESOLUTION_TARGETS: 'readonly', // enhancer.js
  SHAPE_COLORS: 'readonly', // editor.js
  SIZES: 'readonly', // editor.js
  STICKERS: 'readonly', // editor.js
  TEMPLATES: 'readonly', // editor.js
  TEXT_COLORS: 'readonly', // editor.js
  TILDA_TEMPLATES: 'readonly', // editor.js
  _activeEyedropperCleanup: 'readonly', // editor.js
  _applyEraserStamp: 'readonly', // editor.js
  _autosaveTimer: 'readonly', // editor.js
  _cachedDrafts: 'readonly', // editor.js
  _clipboard: 'readonly', // editor.js
  _currentDraftId: 'readonly', // editor.js
  _debounceSaveTimer: 'readonly', // editor.js
  _defringeAndFeatherAlpha: 'readonly', // editor.js
  _eraserHardness: 'readonly', // editor.js
  _eraserMode: 'readonly', // editor.js
  _eraserMouseDownHandler: 'readonly', // editor.js
  _eraserMouseMoveHandler: 'readonly', // editor.js
  _eraserMouseUpHandler: 'readonly', // editor.js
  _eraserOffCanvas: 'readonly', // editor.js
  _eraserOrigCanvas: 'readonly', // editor.js
  _eraserSize: 'readonly', // editor.js
  _eraserSubMode: 'readonly', // editor.js
  _fontApplySeq: 'readonly', // editor.js
  _getLocalImageCoords: 'readonly', // editor.js
  _isErasing: 'readonly', // editor.js
  _lastErasePos: 'readonly', // editor.js
  _magicWandHandler: 'readonly', // editor.js
  _magicWandMode: 'readonly', // editor.js
  _magicWandProcess: 'readonly', // editor.js
  _minDistToBgSamples: 'readonly', // editor.js
  _pencilColor: 'readonly', // editor.js
  _pencilWidth: 'readonly', // editor.js
  _pendingPhotoFile: 'readonly', // editor.js
  _perceptualColorDist: 'readonly', // editor.js
  _sampleBackgroundColors: 'readonly', // editor.js
  activateEyedropper: 'readonly', // editor.js
  activateSelectTool: 'readonly', // editor.js
  addAiElement: 'readonly', // editor.js
  addAiPhotoElement: 'readonly', // editor.js
  addArrow: 'readonly', // editor.js
  addBadge: 'readonly', // editor.js
  addCircle: 'readonly', // editor.js
  addCosmoMascot: 'readonly', // editor.js
  addDashedLine: 'readonly', // editor.js
  addDateBlock: 'readonly', // editor.js
  addFrame: 'readonly', // editor.js
  addHexagon: 'readonly', // editor.js
  addLine: 'readonly', // editor.js
  addPhoto: 'readonly', // editor.js
  addQrCodeToCanvas: 'readonly', // editor.js
  addQuote: 'readonly', // editor.js
  addRect: 'readonly', // editor.js
  addRibbon: 'readonly', // editor.js
  addSpeechBubble: 'readonly', // editor.js
  addStar: 'readonly', // editor.js
  addStickerToCanvas: 'readonly', // editor.js
  addTemplateObj: 'readonly', // editor.js
  addText: 'readonly', // editor.js
  algorithmicFallbackRemoveBg: 'readonly', // workers/bg-removal-worker.js
  alignActiveObject: 'readonly', // editor.js
  applyAutoBalanceToImageData: 'readonly', // enhancer.js
  applyGlow: 'readonly', // editor.js
  applyHdrToCanvas: 'readonly', // enhancer.js
  applyHdrToImageData: 'readonly', // enhancer.js
  applyImageFilter: 'readonly', // editor.js
  applyPendingFont: 'readonly', // editor.js
  applyPickedColor: 'readonly', // editor.js
  applyShapeFillColor: 'readonly', // editor.js
  applyShapeStrokeColor: 'readonly', // editor.js
  applyTextColor: 'readonly', // editor.js
  applyZoom: 'readonly', // editor.js
  bindEvents: 'readonly', // editor.js
  buildBadgeGrid: 'readonly', // editor.js
  buildBgPalette: 'readonly', // editor.js
  buildColorRows: 'readonly', // editor.js
  buildCosmoGrid: 'readonly', // editor.js
  buildFigmaSVG: 'readonly', // editor.js
  buildFontSelect: 'readonly', // editor.js
  buildLogos: 'readonly', // editor.js
  buildTemplates: 'readonly', // editor.js
  buildTildaHTML: 'readonly', // editor.js
  buildVisualFontDropdown: 'readonly', // editor.js
  calculateExportScale: 'readonly', // enhancer.js
  callFigmaProxy: 'readonly', // editor.js
  cancelCanvasEyedropper: 'readonly', // editor.js
  canvas: 'readonly', // editor.js
  checkChronographPosterImport: 'readonly', // editor.js
  clearProps: 'readonly', // editor.js
  closeAiElementModal: 'readonly', // editor.js
  closeBadgeModal: 'readonly', // editor.js
  closeCosmoModal: 'readonly', // editor.js
  closeDraftsModal: 'readonly', // editor.js
  closeEnhancerModal: 'readonly', // editor.js
  closeFigmaExportModal: 'readonly', // editor.js
  closeFigmaImportModal: 'readonly', // editor.js
  closeHdrCompareModal: 'readonly', // editor.js
  closeInstagramRetouchModal: 'readonly', // editor.js
  closeLogoModal: 'readonly', // editor.js
  closeMobileDrawer: 'readonly', // editor.js
  closeOfontModal: 'readonly', // editor.js
  closePhotoImportModal: 'readonly', // editor.js
  closeQrModal: 'readonly', // editor.js
  closeTildaExportModal: 'readonly', // editor.js
  colorToHex: 'readonly', // editor.js
  copyActiveObject: 'readonly', // editor.js
  copyCanvasImageToClipboard: 'readonly', // editor.js
  createProceduralAiElement: 'readonly', // editor.js
  currentAiCategory: 'readonly', // editor.js
  currentExportFormat: 'readonly', // editor.js
  currentExportResolution: 'readonly', // editor.js
  currentHdrPreset: 'readonly', // editor.js
  currentModelLoadPromise: 'readonly', // workers/bg-removal-worker.js
  currentSize: 'readonly', // editor.js
  currentTool: 'readonly', // editor.js
  currentTplCategory: 'readonly', // editor.js
  customFonts: 'readonly', // editor.js
  cycleFontFamily: 'readonly', // editor.js
  debounceEnhancerPreview: 'readonly', // editor.js
  deleteDraftById: 'readonly', // editor.js
  deleteFontFromDB: 'readonly', // editor.js
  doImportFigmaFrame: 'readonly', // editor.js
  downloadBlobOrDataUrl: 'readonly', // editor.js
  duplicateActiveObject: 'readonly', // editor.js
  duplicateAndNudgeActiveObject: 'readonly', // editor.js
  embedAllImagesToBase64: 'readonly', // editor.js
  enhanceFabricImage: 'readonly', // enhancer.js
  enhancerDebounceTimer: 'readonly', // editor.js
  enhancerPreviewObj: 'readonly', // editor.js
  ensureFontAvailable: 'readonly', // editor.js
  escapeHtml: 'readonly', // editor.js
  exportAsOnScreen: 'readonly', // editor.js
  exportFigmaApiSend: 'readonly', // editor.js
  exportFigmaClipboard: 'readonly', // editor.js
  exportFigmaSvg: 'readonly', // editor.js
  exportJpg: 'readonly', // editor.js
  exportPdf: 'readonly', // editor.js
  exportPng: 'readonly', // editor.js
  exportPoster: 'readonly', // enhancer.js
  exportProjectJSON: 'readonly', // editor.js
  exportTildaCopyHtml: 'readonly', // editor.js
  exportTildaDownloadPng: 'readonly', // editor.js
  exportTildaDownloadZip: 'readonly', // editor.js
  exportTildaGenHtml: 'readonly', // editor.js
  exportWebp: 'readonly', // editor.js
  extractFigmaFrames: 'readonly', // editor.js
  fetchFigmaDocument: 'readonly', // editor.js
  figmaColorToRgba: 'readonly', // editor.js
  figmaCurrentDoc: 'readonly', // editor.js
  figmaCurrentFileKey: 'readonly', // editor.js
  figmaFramesList: 'readonly', // editor.js
  figmaLoadedFonts: 'readonly', // editor.js
  figmaSelectedFrameId: 'readonly', // editor.js
  fitActiveObjectToCanvas: 'readonly', // editor.js
  fitZoom: 'readonly', // editor.js
  flipActiveObject: 'readonly', // editor.js
  generateAiElement: 'readonly', // editor.js
  generateBeforeAfterPreview: 'readonly', // enhancer.js
  generateCSSForObject: 'readonly', // editor.js
  generateQrDataUrl: 'readonly', // editor.js
  getAllFontsFromDB: 'readonly', // editor.js
  getArtboardDimensions: 'readonly', // editor.js, enhancer.js
  getEnhancerHdrConfig: 'readonly', // editor.js
  getObjLabel: 'readonly', // editor.js
  getObjMetaSubtitle: 'readonly', // editor.js
  getSavedDrafts: 'readonly', // editor.js
  getStoredFigmaToken: 'readonly', // editor.js
  getTransformers: 'readonly', // workers/bg-removal-worker.js
  gridMode: 'readonly', // editor.js
  groupSelected: 'readonly', // editor.js
  groupSvgBlocks: 'readonly', // editor.js
  handleFontFileSelect: 'readonly', // editor.js
  hideExportLoader: 'readonly', // editor.js
  hideFigmaLoader: 'readonly', // editor.js
  history: 'readonly', // editor.js
  historyIdx: 'readonly', // editor.js
  idbDeleteDraft: 'readonly', // editor.js
  idbGetAllDrafts: 'readonly', // editor.js
  idbSaveDraft: 'readonly', // editor.js
  importProjectJSON: 'readonly', // editor.js
  initAiElementModal: 'readonly', // editor.js
  initCanvas: 'readonly', // editor.js
  initDraftsStorage: 'readonly', // editor.js
  initEnhancerControls: 'readonly', // editor.js
  initEnhancerSplitSlider: 'readonly', // editor.js
  isAiModalInit: 'readonly', // editor.js
  isCanvasDragging: 'readonly', // editor.js
  isEnhancerControlsInit: 'readonly', // editor.js
  isEnhancerSplitDragging: 'readonly', // editor.js
  isExportHdrEnabled: 'readonly', // editor.js
  isExportRunning: 'readonly', // editor.js
  isGridVisible: 'readonly', // editor.js
  isLayerDragging: 'readonly', // editor.js
  isModelLoading: 'readonly', // workers/bg-removal-worker.js
  isPanningMode: 'readonly', // editor.js
  isSnappingEnabled: 'readonly', // editor.js
  isSpacePressed: 'readonly', // editor.js
  lastPanPosX: 'readonly', // editor.js
  lastPanPosY: 'readonly', // editor.js
  layerBringForward: 'readonly', // editor.js
  layerBringToFront: 'readonly', // editor.js
  layerSendBackwards: 'readonly', // editor.js
  layerSendToBack: 'readonly', // editor.js
  loadDraft: 'readonly', // editor.js
  loadDraftById: 'readonly', // editor.js
  loadFigmaFramePreviews: 'readonly', // editor.js
  loadModel: 'readonly', // workers/bg-removal-worker.js
  loadSavedFonts: 'readonly', // editor.js
  loadTemplate: 'readonly', // editor.js
  manualSave: 'readonly', // editor.js
  model: 'readonly', // workers/bg-removal-worker.js
  modelLoadFailed: 'readonly', // workers/bg-removal-worker.js
  normalizeFontName: 'readonly', // editor.js
  normalizeQrText: 'readonly', // editor.js
  onSelection: 'readonly', // editor.js
  openAiElementModal: 'readonly', // editor.js
  openBadgeModal: 'readonly', // editor.js
  openCosmoModal: 'readonly', // editor.js
  openDraftsModal: 'readonly', // editor.js
  openEnhancerModal: 'readonly', // editor.js
  openFigmaExportModal: 'readonly', // editor.js
  openFigmaImportModal: 'readonly', // editor.js
  openFontsDB: 'readonly', // editor.js
  openHdrCompareModal: 'readonly', // editor.js
  openInstagramRetouchModal: 'readonly', // editor.js
  openLogoModal: 'readonly', // editor.js
  openMobileDrawer: 'readonly', // editor.js
  openOfontModal: 'readonly', // editor.js
  openPhotoImportModal: 'readonly', // editor.js
  openPosterDB: 'readonly', // editor.js
  openQrModal: 'readonly', // editor.js
  openTildaExportModal: 'readonly', // editor.js
  parseFigmaUrl: 'readonly', // editor.js
  pasteCopiedObject: 'readonly', // editor.js
  pendingFontBuffer: 'readonly', // editor.js
  pendingFontFileName: 'readonly', // editor.js
  pickColorWithEyeDropper: 'readonly', // editor.js
  printPoster: 'readonly', // editor.js
  processor: 'readonly', // workers/bg-removal-worker.js
  qrCodeInstance: 'readonly', // editor.js
  qrDebounceTimer: 'readonly', // editor.js
  redo: 'readonly', // editor.js
  registerFontFace: 'readonly', // editor.js
  removeBgML: 'readonly', // workers/bg-removal-worker.js
  removeImageBackground: 'readonly', // editor.js
  renderAiElementsGrid: 'readonly', // editor.js
  renderCleanArtboardCanvas: 'readonly', // editor.js, enhancer.js
  renderCustomFontsList: 'readonly', // editor.js
  renderDraftsList: 'readonly', // editor.js
  renderEnhancerSplitPreview: 'readonly', // editor.js
  renderFabricToBuffer: 'readonly', // enhancer.js
  renderFigmaFramesGrid: 'readonly', // editor.js
  renderLayerThumb: 'readonly', // editor.js
  renderQrModalPreview: 'readonly', // editor.js
  renderTemplatesGrid: 'readonly', // editor.js
  resetImageFilters: 'readonly', // editor.js
  restoreHistory: 'readonly', // editor.js
  restoreOriginalFabricImage: 'readonly', // enhancer.js
  revertBackground: 'readonly', // editor.js
  saveCurrentDraft: 'readonly', // editor.js
  saveFontToDB: 'readonly', // editor.js
  saveHistory: 'readonly', // editor.js
  savingHistory: 'readonly', // editor.js
  scheduleAutosave: 'readonly', // editor.js
  selectFigmaFrame: 'readonly', // editor.js
  sendProgress: 'readonly', // workers/bg-removal-worker.js
  separateImageIntoLayers: 'readonly', // editor.js
  setActiveTool: 'readonly', // editor.js
  setEnhancerSplitRatio: 'readonly', // editor.js
  setEraserHardness: 'readonly', // editor.js
  setEraserSize: 'readonly', // editor.js
  setEraserSubMode: 'readonly', // editor.js
  setExportHdr: 'readonly', // editor.js
  setExportResolution: 'readonly', // editor.js
  setFontFamily: 'readonly', // editor.js
  setImageCornerRadius: 'readonly', // editor.js
  setStoredFigmaToken: 'readonly', // editor.js
  showAllLayers: 'readonly', // editor.js
  showExportLoader: 'readonly', // editor.js
  showFigmaLoader: 'readonly', // editor.js
  smartGuides: 'readonly', // editor.js
  startAutosave: 'readonly', // editor.js
  startCanvasEyedropperFallback: 'readonly', // editor.js
  startInlineLayerRename: 'readonly', // editor.js
  switchTildaTab: 'readonly', // editor.js
  syncFontSelectUI: 'readonly', // editor.js
  syncShapeFillColorUI: 'readonly', // editor.js
  syncShapeStrokeColorUI: 'readonly', // editor.js
  syncSwatches: 'readonly', // editor.js
  syncTextColorUI: 'readonly', // editor.js
  syncToggle: 'readonly', // editor.js
  toUtf8: 'readonly', // editor.js
  toast: 'readonly', // editor.js
  toggleCanvasTransparency: 'readonly', // editor.js
  toggleDrawingMode: 'readonly', // editor.js
  toggleEraserMode: 'readonly', // editor.js
  toggleGrid: 'readonly', // editor.js
  toggleLayerShadow: 'readonly', // editor.js
  toggleLockObject: 'readonly', // editor.js
  toggleMagicWandMode: 'readonly', // editor.js
  toggleSnapping: 'readonly', // editor.js
  toggleVisualFontDropdown: 'readonly', // editor.js
  tplSearchQuery: 'readonly', // editor.js
  transformers: 'readonly', // workers/bg-removal-worker.js
  triggerDownload: 'readonly', // enhancer.js
  trySyncToLocalStorage: 'readonly', // editor.js
  undo: 'readonly', // editor.js
  ungroupSelected: 'readonly', // editor.js
  unlockAllLayers: 'readonly', // editor.js
  updateActiveObjectShadow: 'readonly', // editor.js
  updateDraftsBadgeCount: 'readonly', // editor.js
  updateEnhancerMetaResolution: 'readonly', // editor.js
  updateExportProgress: 'readonly', // editor.js
  updateFigmaDimensionsUI: 'readonly', // editor.js
  updateFormatBadge: 'readonly', // editor.js
  updateHistoryBtns: 'readonly', // editor.js
  updateInspectTabUI: 'readonly', // editor.js
  updateLayersList: 'readonly', // editor.js
  updateLockBtnUI: 'readonly', // editor.js
  updateTildaPngSizeLabel: 'readonly', // editor.js
  verifyFigmaTokenQuiet: 'readonly', // editor.js
  withExportCanvasState: 'readonly', // editor.js
  withTimeout: 'readonly', // workers/bg-removal-worker.js
  zoom: 'readonly', // editor.js
};
